class ColorField extends HTMLElement{connectedCallback(){const t=document.querySelector("#colorTemplate").content.cloneNode(true),label=t.querySelector("span"),picker=t.querySelector("[type=color]"),hex=t.querySelector(".hex"),id=this.getAttribute("input-id"),value=this.getAttribute("value")||"#ffffff";label.textContent=this.getAttribute("label");picker.id=id;picker.value=value;hex.value=value.toUpperCase();picker.oninput=()=>{hex.value=picker.value.toUpperCase();update()};hex.onchange=()=>{if(/^#[0-9a-f]{6}$/i.test(hex.value)){picker.value=hex.value;update()}else hex.value=picker.value.toUpperCase()};this.replaceWith(t)}}customElements.define("color-field",ColorField);
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],stage=$("#stage"),telop=$("#telop"),editor=$("#editor");let iconData=null,drag=null,align="left";
const ids=["fontFamily","fontSize","opacity","letterSpacing","lineHeight","bold","italic","vertical","textColor","outlineEnabled","innerColor","innerWidth","outerColor","outerWidth","shadowEnabled","shadowColor","shadowOpacity","shadowDistance","shadowAngle","shadowBlur","backgroundEnabled","backgroundColor","backgroundOpacity","borderRadius","paddingX","paddingY","maxWidth","maxLines","posX","posY","autoWrap","autoFit","safeArea","iconSize","iconGap"];
const v=id=>{const e=$("#"+id);return e.type==="checkbox"?e.checked:e.type==="range"||e.type==="number"?+e.value:e.value};
const rgba=(hex,a)=>{const n=parseInt(hex.slice(1),16);return `rgba(${n>>16},${n>>8&255},${n&255},${a})`};
function outputs(){$$("output[data-for]").forEach(o=>{const id=o.dataset.for,n=v(id),unit={fontSize:"px",opacity:"%",letterSpacing:"px",lineHeight:"%",innerWidth:"px",outerWidth:"px",shadowOpacity:"%",shadowDistance:"px",shadowAngle:"°",shadowBlur:"px",backgroundOpacity:"%",borderRadius:"px",paddingX:"px",paddingY:"px",maxWidth:"px",posX:"%",posY:"%",iconSize:"px",iconGap:"px"}[id]||"";o.textContent=n+unit})}
function cleanHtml(){const d=document.createElement("div");d.innerHTML=editor.innerHTML;d.querySelectorAll("*").forEach(x=>{[...x.attributes].forEach(a=>{if(a.name!=="style")x.removeAttribute(a.name)})});return d.innerHTML}
function update(){outputs();const html=cleanHtml(),font=v("fontFamily"),size=v("fontSize"),weight=v("bold")?900:400,italic=v("italic")?"italic":"normal",opacity=v("opacity")/100,vertical=v("vertical"),inner=v("outlineEnabled")?v("innerWidth"):0,outer=v("outlineEnabled")?v("outerWidth"):0,angle=v("shadowAngle")*Math.PI/180,dist=v("shadowDistance"),sx=Math.cos(angle)*dist,sy=Math.sin(angle)*dist,shadow=v("shadowEnabled")?`${sx}px ${sy}px ${v("shadowBlur")}px ${rgba(v("shadowColor"),v("shadowOpacity")/100)}`:"none";
 $$(".text-layer").forEach(x=>{x.innerHTML=html;x.style.cssText=`font-family:${font};font-size:${size}px;font-weight:${weight};font-style:${italic};opacity:${opacity};letter-spacing:${v("letterSpacing")}px;line-height:${v("lineHeight")/100};text-align:${align};writing-mode:${vertical?"vertical-rl":"horizontal-tb"};max-width:${vertical?"none":v("maxWidth")+"px"};max-height:${vertical?v("maxWidth")+"px":"none"};white-space:${v("autoWrap")?"pre-wrap":"pre"};overflow-wrap:${v("autoWrap")?"break-word":"normal"};`});
 $(".fillLayer").style.color=v("textColor");$(".fillLayer").style.webkitTextStroke="0 transparent";$(".innerLayer").style.color="transparent";$(".innerLayer").style.webkitTextStroke=`${inner*2}px ${v("innerColor")}`;$(".innerLayer").style.paintOrder="stroke fill";$(".outerLayer").style.color="transparent";$(".outerLayer").style.webkitTextStroke=`${(inner+outer)*2}px ${v("outerColor")}`;$(".outerLayer").style.paintOrder="stroke fill";$(".shadowLayer").style.color=v("textColor");$(".shadowLayer").style.webkitTextStroke=`${(inner+outer)*2}px ${v("outerColor")}`;$(".shadowLayer").style.textShadow=shadow;
 const bg=$("#telopBg");bg.style.background=v("backgroundEnabled")?rgba(v("backgroundColor"),v("backgroundOpacity")/100):"transparent";bg.style.borderRadius=v("borderRadius")+"px";telop.style.padding=`${v("paddingY")}px ${v("paddingX")}px`;telop.style.left=v("posX")+"%";telop.style.top=v("posY")+"%";telop.style.gap=v("iconGap")+"px";$("#safeGuide").style.display=v("safeArea")?"block":"none";const iw=$("#iconWrap");iw.style.display=iconData?"block":"none";iw.style.width=iw.style.height=v("iconSize")+"px";if(iconData)$("#iconPreview").src=iconData;limitLines();fit()}
function limitLines(){const max=v("maxLines");$$(".text-layer").forEach(x=>{if(!v("vertical")){x.style.display="-webkit-box";x.style.webkitBoxOrient="vertical";x.style.webkitLineClamp=max;x.style.overflow="hidden"}else{x.style.display="block";x.style.overflow="hidden"}})}
function fit(){telop.style.scale="1";if(!v("autoFit"))return;const maxW=stage.clientWidth*.94,maxH=stage.clientHeight*.92,w=telop.offsetWidth,h=telop.offsetHeight,s=Math.min(1,maxW/w,maxH/h);telop.style.scale=String(s)}
ids.forEach(id=>$("#"+id)?.addEventListener("input",update));editor.addEventListener("input",update);window.addEventListener("resize",update);
$$(".align").forEach(b=>b.onclick=()=>{$$(".align").forEach(x=>x.classList.remove("active"));b.classList.add("active");align=b.dataset.align;update()});
$$("[data-cmd]").forEach(b=>b.onclick=()=>{editor.focus();document.execCommand(b.dataset.cmd);update()});$("#applyColor").onclick=()=>{editor.focus();document.execCommand("foreColor",false,$("#partialColor").value);update()};$("#clearFormat").onclick=()=>{editor.focus();document.execCommand("removeFormat");update()};
$("#addFont").onclick=()=>$("#fontFile").click();$("#fontFile").onchange=async e=>{const f=e.target.files[0];if(!f)return;const name=f.name.replace(/\.[^.]+$/,""),url=URL.createObjectURL(f),face=new FontFace(name,`url(${url})`);await face.load();document.fonts.add(face);$("#fontFamily").add(new Option(name,`"${name}"`));$("#fontFamily").value=`"${name}"`;update()};
$("#chooseIcon").onclick=()=>$("#iconFile").click();$("#iconFile").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{iconData=r.result;update()};r.readAsDataURL(f)};$("#removeIcon").onclick=()=>{iconData=null;update()};
telop.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,px:v("posX"),py:v("posY")};telop.setPointerCapture(e.pointerId)};telop.onpointermove=e=>{if(!drag)return;$("#posX").value=Math.max(0,Math.min(100,drag.px+(e.clientX-drag.x)/stage.clientWidth*100));$("#posY").value=Math.max(0,Math.min(100,drag.py+(e.clientY-drag.y)/stage.clientHeight*100));update()};telop.onpointerup=()=>drag=null;
function state(){return Object.fromEntries(ids.map(id=>[id,v(id)]))}
$("#savePreset").onclick=()=>{const name=prompt("プリセット名","YouTube標準");if(!name)return;localStorage.setItem("telop:"+name,JSON.stringify({settings:state(),html:editor.innerHTML,iconData,align}));presets()};
function presets(){const s=$("#presetList");s.innerHTML='<option value="">プリセットを読み込み…</option>';Object.keys(localStorage).filter(k=>k.startsWith("telop:")).forEach(k=>s.add(new Option(k.slice(6),k)))}
$("#presetList").onchange=e=>{if(!e.target.value)return;const p=JSON.parse(localStorage.getItem(e.target.value));Object.entries(p.settings).forEach(([id,val])=>{const x=$("#"+id);if(x)x.type==="checkbox"?x.checked=val:x.value=val});editor.innerHTML=p.html;iconData=p.iconData;align=p.align;update()};
$("#reset").onclick=()=>{if(confirm("設定を初期化しますか？"))location.reload()};
async function exportPng(){const W=1920,H=1080,scale=W/stage.clientWidth,clone=telop.cloneNode(true);clone.style.left=clone.style.top="0";clone.style.transform="none";clone.style.scale="1";clone.style.position="relative";clone.style.width=telop.offsetWidth+"px";clone.style.height=telop.offsetHeight+"px";const x=v("posX")/100*W-telop.offsetWidth*scale/2,y=v("posY")/100*H-telop.offsetHeight*scale/2,html=`<div xmlns="http://www.w3.org/1999/xhtml" style="width:${W}px;height:${H}px;position:relative;background:transparent"><div style="position:absolute;left:${x}px;top:${y}px;transform:scale(${scale});transform-origin:top left">${clone.outerHTML}</div></div>`,svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}"><foreignObject width="100%" height="100%">${html}</foreignObject></svg>`,blob=new Blob([svg],{type:"image/svg+xml;charset=utf-8"}),url=URL.createObjectURL(blob),img=new Image();img.onload=()=>{const c=document.createElement("canvas");c.width=W;c.height=H;c.getContext("2d").drawImage(img,0,0);URL.revokeObjectURL(url);c.toBlob(b=>{const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="telop.png";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)},"image/png")};img.onerror=()=>alert("PNG生成に失敗しました。別のフォントまたは画像でお試しください。");img.src=url}
$("#download").onclick=exportPng;presets();setTimeout(update,0);
